# Detect OS
if(UNIX)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Android")
        set(PROJECT_OS_NAME "android")
        set(PROJECT_OS_ANDROID ON)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
        set(PROJECT_OS_NAME "linux")
        set(PROJECT_OS_LINUX ON)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
        set(PROJECT_OS_NAME "macos")
        set(PROJECT_OS_MACOS ON)
    else()
        set(PROJECT_OS_NAME "posix")
        set(PROJECT_OS_POSIX ON)
    endif()
elseif(WIN32)
    set(PROJECT_OS_NAME "windows")
    set(PROJECT_OS_WINDOWS ON)
else()
    set(PROJECT_OS_NAME "unknown")
    set(PROJECT_OS_UNKNOWN ON)
endif()
if (PROJECT_OS_UNKNOWN)
    message(WARNING "Unable to detect OS!")
else()
    message(STATUS "Detected OS: ${PROJECT_OS_NAME}")
endif()
