# Configuration for qwertycoind
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'qwertycoind --help' for all available options.

data-dir=/var/lib/qwertycoin
log-file=/var/log/qwertycoin/qwertycoin.log
log-level=0
